import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import { cn } from '@nextui-org/react';
import { Next13NProgress } from 'nextjs13-progress';
import { Toaster } from 'sonner';

import './globals.css';

import { NextUIProvider, ReactQueryProvider } from '~/providers';

const generalSans = localFont({
  src: '../assets/fonts/GeneralSans.ttf',
  display: 'swap',
  variable: '--font-general-sans',
});

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(generalSans.variable, inter.variable)}>
        <Next13NProgress color="#f56630" />
        <Toaster richColors position="top-right" />
        <ReactQueryProvider>
          <NextUIProvider>{children}</NextUIProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
